# This is a basic workflow to help you get started with Actions

name: poc-docker demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
date: "`r format(Sys.time(), '%d %B, %Y')`"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      d1: echo "${date +%Y%m%d_%H%M%S}"
      d2: echo "$(date +%Y%m%d_%H%M%S)"
      d3: echo "date +%Y%m%d_%H%M%S"
      zip_name1: rf-test-result-"${d1}"
      zip_name2: rf-test-result-"${d2}"
      zip_name3: rf-test-result-"${d3}"
      
      ppk:  "`r format(Sys.date(), '%d %B, %Y')`"
      

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
#       - name: Pip install from requirements.txt file
#         run: |
#           python -m pip install -r RF/requirements.txt
          
#       - name: Run a script
#         run: robot -v ENV:staging RF/test_cases
        
      - name: echo env
 
          
#       - name: Generate report
#         uses: actions/upload-artifact@v2
#         with:
#           name: "${zip_name}"
#           path: |
#             /home/runner/work/poc_docker/poc_docker/output.xml
#             /home/runner/work/poc_docker/poc_docker/log.html
#             /home/runner/work/poc_docker/poc_docker/report.html
